### ISSUE TITLE
P13 Typo

### ISSUE THREAD

**Issue by etodd** [MakeSchool-Tutorials/Swift-Language-Playgrounds#13]
`bob.newStudents` and `harry.newStudents`

Should be `numStudents`, not `newStudents`

**Comment by cliffweitzman** [comment]
On line 32, I would change "Try making this change to the above code now." to "Try making this change to the above code on line 7 now." Since, numStudents is used both on line 7 and line 12:  in one case it is declared and in the other it is initialized, students may make the change to line 12 and be confused, not realizing why their change is resulting in an error.
![image](https://cloud.githubusercontent.com/assets/3460171/15914666/aff15a5c-2d97-11e6-9447-29f06ffe6b01.png)

**Comment by cliffweitzman** [comment]
Currently, we declare three students, bob, harry and jessica.
![image](https://cloud.githubusercontent.com/assets/3460171/15914721/214f0906-2d98-11e6-8e90-f2b4163d124e.png)
But on line 42, instructions are only given for modifying bob and harry, and not jessica, this results in an error. Dion mentioned that jessica was added later for gender balance and that the best way to solve this is simply to remove the declaration of/all references to harry, and to change line 42 from:

"Do the same thing to the statements `bob.newStudents` and `harry.newStudents`. Notice as each student is initialized, the `numStudents` value increases by 1!"
to 
"Next, change `bob.numStudents` to 'Student.numStudents' and `jessica.numStudents` to 'Student.numStudents'. Notice as each student is initialized, the `numStudents` value increases by 1!"

**Comment by dionlarson** [comment]
fd526c6
