### ISSUE TITLE
P09 Functions Challenge

### ISSUE THREAD

**Issue by Frostao** [MakeSchool-Tutorials/Swift-Language-Playgrounds#19]
Suppose I want to get the perimeter and area of a rectangle, how would you write a readable function that can take length and width as parameters and return its perimeter and area?

Solution

``` swift
func calcRectangle(fromLength length:Double, fromWidth width:Double) -> (perimeter:Double, area:Double) {
    return (2*(length+width), length*width)
}
```

**Comment by zontan** [comment]
In the vein of building on the resize() method at the bottom of the chapter - how would you alter the function to resize a circle? What parameters would you use to define a circle, and what would need to change?

Ideally, the answer would look something like:

`func resizeCircle(centerX: Int, centerY: Int, fromRadius: Int, toRadius: Int)`

since resizing a circle only involves changing the radius, not the center point.
