### ISSUE TITLE
P11 Classes and Structs Challenge

### ISSUE THREAD

**Issue by john-b-yang** [MakeSchool-Tutorials/Swift-Language-Playgrounds#31]
P11 - Classes and Structs:

Conceptual Question - Which of the following objects would be better modeled as a class or as a struct?
a. A House - A Class, because different houses have different internal decorations
b. A Bicycle - A Struct, because bicycles are all built the same way
c. A Company - A Class, because each company has different business models / products and subclasses can be made to emulate different individuals.
Can you come up with an everyday object that would be better modeled by one or the other?

A Coding / Organizational Question: Design (not necessarily code) an organization of classes and subclasses that could model one of the following:
a. A School
b. A Sports Team
c. A Tech Company

**Comment by soggybag** [comment]
I would add this to the discussion:

While structs and classes act the same in many places when thinking about usage you would use a class when identity is important. 

An analogy, you could say structs would be good for things like a school lunch. All of the school lunches have a main course, side, and desert. It doesn't matter who gets a lunch since the one lunch with the same value is the same as another. Students in a school on the other hand have identity, even if their values are the same, imagine two students named John, that are in grade 4. You can't send the either home with either set of parents. Parents expect their own child. 

A practical example. Imagine a list of contacts. Your app passes these contacts to another view where the contact information can be edited. Imagine the struct passed to the editing view. Using a struct here doesn't work the struct lacks identity it isn't tied to a unique element. Using a class for this on the other hand works. Because the element passed to your editing view represents a reference to a single unique element.

The concept of identity is a question you can ask yourself when building an app. Does this element need to have a unique identity? 

Examples: CGPoint holds two numbers representing the position on the screen. This doesn't require identity. You can use any CGPoint to set the location of a view. You can pass a CGPoint into a function that calculates a new position, and get a different CGPoint in return. 

UIView represents a view on the screen. You may have multiple variables referencing this object and it's important that they all reference the same view.
