### ISSUE TITLE
P3 : Strings

### ISSUE THREAD

**Issue by funzaAcademy** [MakeSchool-Tutorials/Swift-Language-Playgrounds#9]
let season = "winter"
let salutation = "Have a nice " + season + "!"

Modify the above code to display the following line:

Have a nice "Winter"

Note:  This demonstrates _Escape_ characters

**Comment by nikolasburk** [comment]
Not sure what others think about this but in the last section about value semantics, I would completely omit the second part explaining that Swift is smart enough to only _actually_ copy a `String` once its modified. 

I would argue that at this point for the student it's only important to understand the actual behaviour of a `String` as perceived by the programmer, not so much what's happening under the hood (it shortly confused me when reading it, that's why I bring it up).

**Comment by funzaAcademy** [comment]
let barnResidents = "🐮🐔🐷🐴"
let position = 2
let index = barnResidents.startIndex.advancedBy(position)

What is the _Type_ of the _index_ constant ?
a. Integer
b. Index

**Comment by cliffweitzman** [comment]
Make a variable for your name. Using your name variable, write a print statement that results in a sentence introducing yourself.

Declare String variables for your 4 favorite foods. 
Declare a new String variable, myFoods, in which you connect your favorite foods in one line
, starting with food1 and ending with food4, using “ and “ in-between each food.

//myFoods:String = 

Using the myFoods variable. Assign the third character from that variable to a new, thirdCharacter variable.

//var thirdCharacter: Character =

Using the myFoods variable and the componentsSeparatedByString() method, print the name of each one of your favorite foods
